#allan = bool(input('digite um valor: '))
#print(allan) 
#zeus = float(input('digiteb um valor:'))
#print(zeus)
#priscila = str(input('digite um valor:'))
#print(priscila)
# m = str(input('digite um valor:'))
#print (type(m))
#m = input('digite algo:')
#print(m.isnumeric())
#casa = input('digite algo:')
#print(casa.isalpha())
#ba = input('digite algo:')
#print(ba.isdecimal())
#qwe = input('digite algo')
#print(qwe.isalnum())
